export const settings = {
    minSecurityLevelOffset: 1,
    maxMoneyMultiplayer: 0.9,
    minSecurityWeight: 100,
    mapRefreshInterval: 24 * 60 * 60 * 1000,
    keys: {
        serverMap: 'BB_SERVER_MAP',
        hackTarget: 'BB_HACK_TARGET',
        action: 'BB_ACTION',
        crimesStop: 'BB_CRIMES_STOP',
        buyEquipment: 'BB_BUY_EQUIPMENT',
        doAscension: 'BB_DO_ASCENSION',
        strAscMultHardLimit: 'BB_STR_ASC_MULT_HARD_LIMIT',
        equipmentList: 'BB_EQUIPMENT_LIST',
        augumentationList: 'BB_AUGUMENTATION_LIST',

    },
    crimes: [
        'shoplift',
        'rob store',
        'mug',
        'larceny',
        'deal drugs',
        'bond forgery',
        'traffick arms',
        'homicide',
        'grand theft auto',
        'kidnap',
        'assassinate',
        'heist',
    ],
    gangMemberNamesList : [
        'Darth Vader',
        'Joker',
        'Two-Face',
        'Warden Norton',
        'Hannibal Lecter',
        'Sauron',
        'Bane',
        'Tyler Durden',
        'Agent Smith',
        'Gollum',
        'Vincent Vega',
        'Saruman',
        'Loki',
        'Vito Corleone',
        'Balrog',
        'Palpatine',
        'Michael Corleone',
        'Talia al Ghul',
        'John Doe',
        'Scarecrow',
        'Commodus',
        'Jabba the Hutt',
        'Scar',
        'Grand Moff Tarkin',
        'Boba Fett',
        'Thanos',
        'Terminator',
        'Frank Costello',
        'Hector Barbossa',
        'Xenomorph',
    ],
    equipmentTypes : [
        'Weapon',
        'Armor',
        'Vehicle',
        'Rootkit',
        'Augmentation'],
    hackPrograms : [
        'BruteSSH.exe',
        'FTPCrack.exe',
        'relaySMTP.exe',
        'HTTPWorm.exe',
        'SQLInject.exe'
    ],
    hackScripts : [
        'hack.js',
        'grow.js',
        'weaken.js'
    ],
    homeRamReserved: 20,
    homeRamReservedBase: 20,
    homeRamExtraRamReserved: 12,
    homeRamBigMode: 64,
    maxWeakenTime: 30 * 60 * 1000,
    changes: {
        hack: 0.002,
        grow: 0.004,
        weaken: 0.05,
    },
    maxPlayerServers: 25,
    gbRamCost: 55000,
    maxGbRam: 1048576,
    minGbRam: 64,
    totalMoneyAllocation: 0.9,
    actions: {
        BUY: 'buy',
        UPGRADE: 'upgrade',
    },
    intervalToRecheck: 10000
}